version: '3.3'
services:
    ollama-webui:
        ports:
            - '10220:8080'
        container_name: ollama-webui
        image: ollamawebui/ollama-webui
    ollama:
        volumes:
            - '/home/user/.ollama:/root/.ollama'
        ports:
            - '11434:11434'
        environment:
            - 'OLLAMA_ORIGINS=*'
        container_name: ollama
        image: ollama/ollama
        deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  count: 1
                  capabilities: [gpu]
