#!/usr/bin/env bash
git submodule add --force https://github.com/gravitl/netmaker devops/netmaker
git submodule add --force https://github.com/hobby-kube/guide devops/k8s-guide
git submodule add --force https://github.com/nocodb/nocodb misc/nocodb
git submodule add --force https://github.com/ethibox/awesome-stacks misc/awesome-stacks
git submodule add --force https://github.com/rvaiya/warpd misc/warpd
git submodule add --force https://github.com/overleaf/overleaf misc/overleaf
git submodule add --force https://github.com/TeamPiped/Piped-Docker misc/Piped-Docker
git submodule add --force https://github.com/deviantony/docker-elk misc/docker-elk
git submodule add --force https://github.com/misterch0c/CrimeBoards misc/CrimeBoards
git submodule add --force https://github.com/misterch0c/what_is_this_c2 misc/what_is_this_c2
git submodule add --force https://github.com/jessfraz/dockerfiles misc/jessfraz-dockerfiles
git submodule add --force https://github.com/StevenBlack/hosts misc/StevenBlack-hosts
git submodule add --force https://github.com/NixOS/nixpkgs misc/nixpkgs
git submodule add --force https://github.com/CompVis/stable-diffusion misc/stable-diffusion
#git submodule add --force https://github.com/Red-Laboratory/Malware-collection misc/Malware-collection
git submodule add --force https://github.com/chrislgarry/Apollo-11 misc/Apollo-11
git submodule add --force https://github.com/daviddao/awful-ai misc/awful-ai
git submodule add --force https://github.com/tylertreat/comcast misc/comcast
git submodule add --force https://github.com/kootenpv/whereami misc/whereami
git submodule add --force https://github.com/kdn251/interviews misc/interviews
git submodule add --force https://github.com/0x192/universal-android-debloater misc/universal-android-debloater
git submodule add --force https://github.com/tensorflow/models misc/tensorflow-models
git submodule add --force https://github.com/docker/awesome-compose misc/awesome-compose
git submodule add --force https://github.com/Igglybuff/awesome-piracy misc/awesome-piracy
git submodule add --force https://github.com/iptv-org/iptv misc/iptv
git submodule add --force https://github.com/invoke-ai/InvokeAI misc/InvokeAI
git submodule add --force https://github.com/AykutSarac/jsoncrack.com misc/jsoncrack.com
git submodule add --force https://github.com/trimstray/technical-whitepapers $HOME/pdfs/education/technical-whitepapers
git submodule add --force https://github.com/arkadiyt/bounty-targets-data bug-bounty/bounty-targets-data
git submodule add --force https://github.com/bobby-lin/study-bug-bounty bug-bounty/study-bug-bounty
git submodule add --force https://github.com/open-guides/og-aws education/og-aws
git submodule add --force https://github.com/OpenZeppelin/awesome-openzeppelin education/awesome-openzeppelin
git submodule add --force https://github.com/smartcontractkit/full-blockchain-solidity-course-py education/full-blockchain-solidity-course-py
git submodule add --force https://github.com/anderspitman/awesome-tunneling education/awesome-tunneling
git submodule add --force https://github.com/ConsenSys/smart-contract-best-practices education/smart-contract-best-practices
git submodule add --force https://github.com/papers-we-love/papers-we-love education/papers-we-love
git submodule add --force https://github.com/public-apis/public-apis education/public-apis
git submodule add --force https://github.com/sindresorhus/awesome education/awesome
git submodule add --force https://github.com/EbookFoundation/free-programming-books education/free-programming-books
git submodule add --force https://github.com/jwasham/coding-interview-university education/coding-interview-university
git submodule add --force https://github.com/awesome-selfhosted/awesome-selfhosted education/awesome-selfhosted
git submodule add --force https://github.com/veggiemonk/awesome-docker education/awesome-docker
git submodule add --force https://github.com/DopplerHQ/awesome-interview-questions education/awesome-interview-questions
git submodule add --force https://github.com/faif/python-patterns education/python-patterns
git submodule add --force https://github.com/bregman-arie/devops-exercises education/devops-exercises
git submodule add --force https://github.com/MichaelCade/90DaysOfDevOps education/90DaysOfDevOps
git submodule add --force https://github.com/veeral-patel/how-to-secure-anything education/how-to-secure-anything
git submodule add --force https://github.com/jlevy/the-art-of-command-line education/the-art-of-command-line
git submodule add --force https://github.com/0xAX/linux-insides education/linux-insides
git submodule add --force https://github.com/0xricksanchez/paper_collection education/paper_collection
git submodule add --force https://github.com/hackerkid/Mind-Expanding-Books education/Mind-Expanding-Books
git submodule add --force https://github.com/microsoft/ML-For-Beginners education/ML-For-Beginners
git submodule add --force https://github.com/sobolevn/awesome-cryptography education/awesome-cryptography
git submodule add --force https://github.com/lfit/itpol education/itpol
git submodule add --force https://github.com/alex/what-happens-when education/what-happens-when
git submodule add --force https://github.com/sdmg15/Best-websites-a-programmer-should-visit education/Best-websites-a-programmer-should-visit
git submodule add --force https://github.com/tsiege/Tech-Interview-Cheat-Sheet education/Tech-Interview-Cheat-Sheet
git submodule add --force https://github.com/cfenollosa/os-tutorial education/os-tutorial
git submodule add --force https://github.com/GorvGoyl/Clone-Wars education/Clone-Wars
git submodule add --force https://github.com/kkuchta/css-only-chat education/css-only-chat
git submodule add --force https://github.com/karan/Projects education/karan-Projects
git submodule add --force https://github.com/abduvik/just-enough-series education/just-enough-series
git submodule add --force https://github.com/ibraheemdev/modern-unix education/modern-unix
git submodule add --force https://github.com/kamranahmedse/developer-roadmap education/developer-roadmap
git submodule add --force https://github.com/rShetty/awesome-podcasts education/awesome-podcasts
git submodule add --force https://github.com/practical-tutorials/project-based-learning education/project-based-learning
git submodule add --force https://github.com/Developer-Y/cs-video-courses education/cs-video-courses
git submodule add --force https://github.com/drduh/macOS-Security-and-Privacy-Guide education/macOS-Security-and-Privacy-Guide
git submodule add --force https://github.com/TheAlgorithms/Python education/TheAlgorithmsPython
git submodule add --force https://github.com/learn-anything/youtube education/learn-anything-youtube
git submodule add --force https://github.com/PrejudiceNeutrino/YouTube_Channels education/YouTube_Channels
git submodule add --force https://github.com/zero-to-mastery/resources education/zero-to-mastery-resources
git submodule add --force https://github.com/onceupon/Bash-Oneliner education/Bash-Oneliner
git submodule add --force https://github.com/kuchin/awesome-cto education/awesome-cto
git submodule add --force https://github.com/docker/labs education/docker-labs
git submodule add --force https://github.com/eon01/DockerCheatSheet education/DockerCheatSheet
git submodule add --force https://github.com/trimstray/the-practical-linux-hardening-guide education/the-practical-linux-hardening-guide
git submodule add --force https://github.com/upgundecha/howtheysre education/howtheysre
git submodule add --force https://github.com/mtdvio/every-programmer-should-know education/every-programmer-should-know
git submodule add --force https://github.com/krol3/container-security-checklist education/container-security-checklist
git submodule add --force https://github.com/nowsecure/secure-mobile-development pentest-education/secure-mobile-development
git submodule add --force https://github.com/nixawk/pentest-wiki pentest-education/pentest-wiki
git submodule add --force https://github.com/vulhub/vulhub pentest-education/vulhub
git submodule add --force https://github.com/nixawk/labs pentest-education/nixawk_labs
git submodule add --force https://github.com/Lissy93/personal-security-checklist pentest-education/personal-security-checklist
git submodule add --force https://github.com/HalbornSecurity/PublicReports pentest-education/HalbornPublicReports
git submodule add --force https://github.com/toniblyx/my-arsenal-of-aws-security-tools pentest-education/my-arsenal-of-aws-security-tools
git submodule add --force https://github.com/jassics/awesome-aws-security pentest-education/awesome-aws-security
git submodule add --force https://github.com/mytechnotalent/Reverse-Engineering pentest-education/Reverse-Engineering
git submodule add --force https://github.com/sundowndev/hacker-roadmap pentest-education/hacker-roadmap
git submodule add --force https://github.com/The-Art-of-Hacking/h4cker pentest-education/h4cker
git submodule add --force https://github.com/vitalysim/Awesome-Hacking-Resources pentest-education/Awesome-Hacking-Resources
git submodule add --force https://github.com/mantvydasb/RedTeam-Tactics-and-Techniques pentest-education/RedTeam-Tactics-and-Techniques
git submodule add --force https://github.com/irsdl/top10webseclist pentest-education/top10webseclist
git submodule add --force https://github.com/carpedm20/awesome-hacking pentest-education/awesome-hacking
git submodule add --force https://github.com/ashishb/android-security-awesome pentest-education/android-security-awesome
git submodule add --force https://github.com/apsdehal/awesome-ctf pentest-education/awesome-ctf
git submodule add --force https://github.com/arainho/awesome-api-security pentest-education/awesome-api-security
git submodule add --force https://github.com/S3cur3Th1sSh1t/Pentest-Tools pentest-education/Pentest-Tools
git submodule add --force https://github.com/coreb1t/awesome-pentest-cheat-sheets pentest-education/awesome-pentest-cheat-sheets
git submodule add --force https://github.com/Kitsun3Sec/Pentest-Cheat-Sheets pentest-education/Pentest-Cheat-Sheets
git submodule add --force https://github.com/qazbnm456/awesome-web-security pentest-education/awesome-web-security
git submodule add --force https://github.com/paralax/awesome-honeypots pentest-education/awesome-honeypots
git submodule add --force https://github.com/paragonie/awesome-appsec pentest-education/awesome-appsec
git submodule add --force https://github.com/vaib25vicky/awesome-mobile-security pentest-education/awesome-mobile-security
git submodule add --force https://github.com/GrrrDog/Java-Deserialization-Cheat-Sheet pentest-education/Java-Deserialization-Cheat-Sheet
git submodule add --force https://github.com/ihebski/DefaultCreds-cheat-sheet pentest-education/DefaultCreds-cheat-sheet
git submodule add --force https://github.com/S1ckB0y1337/Active-Directory-Exploitation-Cheat-Sheet pentest-education/Active-Directory-Exploitation-Cheat-Sheet
git submodule add --force https://github.com/OlivierLaflamme/Cheatsheet-God pentest-education/Cheatsheet-God
git submodule add --force https://github.com/blaCCkHatHacEEkr/PENTESTING-BIBLE pentest-education/PENTESTING-BIBLE
git submodule add --force https://github.com/sinfulz/JustTryHarder pentest-education/JustTryHarder
git submodule add --force https://github.com/offensive-security/exploitdb pentest-education/exploitdb
git submodule add --force https://github.com/Muhammd/Awesome-Pentest pentest-education/Awesome-Pentest
git submodule add --force https://github.com/sbilly/awesome-security pentest-education/awesome-security
git submodule add --force https://github.com/trimstray/test-your-sysadmin-skills pentest-education/test-your-sysadmin-skills
git submodule add --force https://github.com/imthenachoman/How-To-Secure-A-Linux-Server pentest-education/How-To-Secure-A-Linux-Server
git submodule add --force https://github.com/Hacker0x01/hacker101 pentest-education/hacker101
git submodule add --force https://github.com/shieldfy/API-Security-Checklist pentest-education/API-Security-Checklist
git submodule add --force https://github.com/google/google-ctf pentest-education/google-ctf
git submodule add --force https://github.com/madhuakula/kubernetes-goat pentest-education/kubernetes-goat
git submodule add --force https://github.com/OWASP/CheatSheetSeries pentest-education/CheatSheetSeries
git submodule add --force https://github.com/swisskyrepo/PayloadsAllTheThings pentest-education/PayloadsAllTheThings
git submodule add --force https://github.com/enaqx/awesome-pentest pentest-education/awesome-pentest
git submodule add --force https://github.com/bayandin/awesome-awesomeness pentest-education/awesome-awesomeness
git submodule add --force https://github.com/trimstray/the-book-of-secret-knowledge pentest-education/the-book-of-secret-knowledge
git submodule add --force https://github.com/Hack-with-Github/Awesome-Hacking pentest-education/Awesome-Hacking
git submodule add --force https://github.com/juliocesarfort/public-pentesting-reports pentest-education/public-pentesting-reports
git submodule add --force https://github.com/Sector443/awesome-list-of-public-pentesting-reports pentest-education/awesome-list-of-public-pentesting-reports
git submodule add --force https://github.com/OWASP/railsgoat pentest-education/railsgoat
git submodule add --force https://github.com/nahamsec/Resources-for-Beginner-Bug-Bounty-Hunters pentest-education/Resources-for-Beginner-Bug-Bounty-Hunters
git submodule add --force https://github.com/HarmJ0y/CheatSheets pentest-education/HarmJ0y-CheatSheets
git submodule add --force https://github.com/trailofbits/ctf pentest-education/trailofbits-ctf
git submodule add --force https://github.com/trailofbits/publications pentest-education/trailofbits-publications
git submodule add --force https://github.com/RistBS/Awesome-RedTeam-Cheatsheet pentest-education/Awesome-RedTeam-Cheatsheet
git submodule add --force https://github.com/dsopas/assessment-mindset pentest-education/assessment-mindset
git submodule add --force https://github.com/rmusser01/Infosec_Reference pentest-education/Infosec_Reference
git submodule add --force https://github.com/EdOverflow/bugbounty-cheatsheet pentest-education/bugbounty-cheatsheet
git submodule add --force https://github.com/decalage2/awesome-security-hardening pentest-education/awesome-security-hardening
git submodule add --force https://github.com/OWASP/Top10 pentest-education/Top10
git submodule add --force https://github.com/mikeroyal/Open-Source-Security-Guide pentest-education/Open-Source-Security-Guide
git submodule add --force https://github.com/riramar/Web-Attack-Cheat-Sheet pentest-education/Web-Attack-Cheat-Sheet
git submodule add --force https://github.com/brootware/awesome-cyber-security-university pentest-education/awesome-cyber-security-university
git submodule add --force https://github.com/rshipp/awesome-malware-analysis pentest-education/awesome-malware-analysis
git submodule add --force https://github.com/daviddias/awesome-hacking-locations pentest-education/awesome-hacking-locations
git submodule add --force https://github.com/fabacab/awesome-lockpicking pentest-education/awesome-lockpicking
git submodule add --force https://github.com/cpuu/awesome-fuzzing pentest-education/awesome-fuzzing
git submodule add --force https://github.com/fkie-cad/awesome-embedded-and-iot-security pentest-education/awesome-embedded-and-iot-security
git submodule add --force https://github.com/dhondta/awesome-executable-packing pentest-education/awesome-executable-packing
git submodule add --force https://github.com/muhammet-mucahit/Security-Exercises pentest-education/Security-Exercises
git submodule add --force https://github.com/A0RX/Red-Blueteam-party pentest-education/Red-Blueteam-party
git submodule add --force https://github.com/0xMrNiko/Awesome-Red-Teaming pentest-education/Awesome-Red-Teaming
git submodule add --force https://github.com/J0hnbX/RedTeam-Resources pentest-education/RedTeam-Resources
git submodule add --force https://github.com/karimhabush/cyberowl pentest-education/cyberowl
git submodule add --force https://github.com/husnainfareed/Awesome-Ethical-Hacking-Resources pentest-education/Awesome-Ethical-Hacking-Resources
git submodule add --force https://github.com/pop3ret/AWSome-Pentesting pentest-education/AWSome-Pentesting
git submodule add --force https://github.com/dwisiswant0/awesome-oneliner-bugbounty pentest-education/awesome-oneliner-bugbounty
git submodule add --force https://github.com/Hack-with-Github/Free-Security-eBooks pentest-education/Free-Security-eBooks
git submodule add --force https://github.com/PaulSec/awesome-sec-talks pentest-education/awesome-sec-talks
git submodule add --force https://github.com/ine-labs/AWSGoat pentest-education/AWSGoat
git submodule add --force https://github.com/ine-labs/AzureGoat pentest-education/AzureGoat
git submodule add --force https://github.com/snoopysecurity/dvws-node pentest-education/dvws-node
git submodule add --force https://github.com/logicalhacking/DVHMA pentest-education/DVHMA
git submodule add --force https://github.com/cider-security-research/cicd-goat pentest-education/cicd-goat
git submodule add --force https://github.com/erev0s/VAmPI pentest-education/VAmPI
git submodule add --force https://github.com/OWASP/DVSA pentest-education/DVSA
git submodule add --force https://github.com/srini0x00/dvta pentest-education/dvta
git submodule add --force https://github.com/appsecco/dvja pentest-education/dvja
git submodule add --force https://github.com/anxolerd/dvpwa pentest-education/dvpwa
git submodule add --force https://github.com/rewanthtammana/Damn-Vulnerable-Bank pentest-education/Damn-Vulnerable-Bank
git submodule add --force https://github.com/prateek147/DVIA-v2 pentest-education/DVIA-v2
git submodule add --force https://github.com/praetorian-inc/DVRF pentest-education/DVRF
git submodule add --force https://github.com/we45/DVFaaS-Damn-Vulnerable-Functions-as-a-Service pentest-education/DVFaaS
git submodule add --force https://github.com/m6a-UdS/dvca pentest-education/dvca
git submodule add --force https://github.com/appsecco/dvcsharp-api pentest-education/dvcsharp-api
git submodule add --force https://github.com/payatu/Tiredful-API pentest-education/Tiredful-API
git submodule add --force https://github.com/dolevf/Damn-Vulnerable-GraphQL-Application pentest-education/Damn-Vulnerable-GraphQL-Application
git submodule add --force https://github.com/kurogai/100-redteam-projects pentest-education/100-redteam-projects
git submodule add --force https://github.com/TCM-Course-Resources/Practical-Ethical-Hacking-Resources pentest-education/Practical-Ethical-Hacking-Resources
git submodule add --force https://github.com/infosecn1nja/AD-Attack-Defense pentest-education/AD-Attack-Defense
git submodule add --force https://github.com/Integration-IT/Active-Directory-Exploitation-Cheat-Sheet pentest-education/Active-Directory-Exploitation-Cheat-Sheet-IIT
git submodule add --force https://github.com/WazeHell/vulnerable-AD pentest-education/vulnerable-AD
git submodule add --force https://github.com/samratashok/nishang pentest-education/nishang
git submodule add --force https://github.com/hslatman/awesome-threat-intelligence pentest-education/awesome-threat-intelligence
git submodule add --force https://github.com/0xInfection/Awesome-WAF pentest-education/Awesome-WAF
git submodule add --force https://github.com/arch3rPro/PentestTools pentest-education/PentestTools
git submodule add --force https://github.com/cugu/awesome-forensics pentest-education/awesome-forensics
git submodule add --force https://github.com/SunWeb3Sec/DeFiHackLabs pentest-education/DeFiHackLabs
git submodule add --force https://github.com/We5ter/Awesome-DevSecOps-Platforms pentest-education/Awesome-DevSecOps-Platforms
git submodule add --force https://github.com/The-Viper-One/Pentest-Everything pentest-education/Pentest-Everything
git submodule add --force https://github.com/V33RU/IoTSecurity101 pentest-education/IoTSecurity101
git submodule add --force https://github.com/brcyrr/PracticalCyberSecurityResources pentest-education/PracticalCyberSecurityResources
git submodule add --force https://github.com/wwong99/pentest-notes pentest-education/pentest-notes
git submodule add --force https://github.com/Anugrahsr/Awesome-web3-Security pentest-education/Awesome-web3-Security
git submodule add --force https://github.com/PaulSec/awesome-windows-domain-hardening pentest-education/awesome-windows-domain-hardening
git submodule add --force https://github.com/fabacab/awesome-cybersecurity-blueteam pentest-education/awesome-cybersecurity-blueteam
git submodule add --force https://github.com/meirwah/awesome-incident-response pentest-education/awesome-incident-response
git submodule add --force https://github.com/TaptuIT/awesome-devsecops pentest-education/awesome-devsecops
git submodule add --force https://github.com/mandiant/red_team_tool_countermeasures pentest-education/red_team_tool_countermeasures
git submodule add --force https://github.com/LetsDefend/SOC-Interview-Questions pentest-education/SOC-Interview-Questions
git submodule add --force https://github.com/jivoi/awesome-osint pentest-education/awesome-osint
git submodule add --force https://github.com/jakejarvis/awesome-shodan-queries pentest-education/awesome-shodan-queries
git submodule add --force https://github.com/cipher387/Dorks-collections-list  pentest-education/Dorks-collections-list
git submodule add --force https://github.com/techgaun/github-dorks pentest-education/github-dorks
git submodule add --force https://github.com/edoardottt/awesome-hacker-search-engines pentest-education/awesome-hacker-search-engines
git submodule add --force https://github.com/OWASP/wstg pentest-frameworks/wstg
git submodule add --force https://github.com/OWASP/owasp-mstg pentest-frameworks/owasp-mstg
git submodule add --force https://github.com/s0md3v/Corsy pentest-tools/Corsy
git submodule add --force https://github.com/epinna/tplmap pentest-tools/tplmap
git submodule add --force https://github.com/crawlab-team/crawlab pentest-tools/crawlab
git submodule add --force https://github.com/epi052/feroxbuster pentest-tools/feroxbuster
git submodule add --force https://github.com/flipkart-incubator/Astra pentest-tools/Astra
git submodule add --force https://github.com/pwndoc/pwndoc pentest-tools/pwndoc
git submodule add --force https://github.com/gwen001/pentest-tools pentest-tools/gwen001-pentest-tools
git submodule add --force https://github.com/ethibox/awesome-stacks pentest-tools/awesome-stacks
git submodule add --force https://github.com/portainer/portainer pentest-tools/portainer
git submodule add --force https://github.com/LasCC/Hack-Tools pentest-tools/Hack-Tools
git submodule add --force https://github.com/commixproject/commix pentest-tools/commix
git submodule add --force https://github.com/qeeqbox/social-analyzer pentest-tools/social-analyzer
git submodule add --force https://github.com/zaproxy/zaproxy pentest-tools/zaproxy
git submodule add --force https://github.com/carlospolop/PEASS-ng pentest-tools/PEASS-ng
git submodule add --force https://github.com/techgaun/github-dorks pentest-tools/github-dorks
git submodule add --force https://github.com/maK-/parameth pentest-tools/parameth
git submodule add --force https://github.com/Sh1Yo/x8 pentest-tools/x8
git submodule add --force https://github.com/vishnudxb/automated-pentest pentest-tools/automated-pentest
git submodule add --force https://github.com/carlospolop/hacktricks pentest-tools/hacktricks
git submodule add --force https://gitlab.com/invuls/pentest-projects/pcf pentest-tools/pcf
git submodule add --force https://github.com/Nightbringer21/fridump pentest-tools/fridump
git submodule add --force https://github.com/caddyserver/caddy pentest-tools/caddy
git submodule add --force https://github.com/mzet-/linux-exploit-suggester pentest-tools/linux-exploit-suggester
git submodule add --force https://github.com/va1da5/docker-objection-for-android misc/objection
git submodule add --force https://github.com/iddoeldor/frida-snippets misc/frida-snippets
git submodule add --force https://github.com/cybersecsi/RAUDI pentest-tools/RAUDI
git submodule add --force https://github.com/sullo/nikto pentest-tools/nikto
git submodule add --force https://github.com/sherlock-project/sherlock pentest-tools/sherlock
git submodule add --force https://github.com/ivre/ivre pentest-tools/ivre
git submodule add --force https://github.com/wapiti-scanner/wapiti pentest-tools/wapiti
git submodule add --force https://github.com/google/tsunami-security-scanner pentest-tools/tsunami-security-scanner
git submodule add --force https://github.com/vletoux/pingcastle pentest-tools/pingcastle
git submodule add --force https://github.com/BloodHoundAD/BloodHound pentest-tools/BloodHound
git submodule add --force https://github.com/n1nj4sec/pupy pentest-tools/pupy
git submodule add --force https://github.com/google/oss-fuzz pentest-tools/oss-fuzz
git submodule add --force https://github.com/internetwache/GitTools pentest-tools/GitTools
git submodule add --force https://github.com/S3cur3Th1sSh1t/WinPwn pentest-tools/WinPwn
git submodule add --force https://github.com/liamg/traitor pentest-tools/traitor
git submodule add --force https://github.com/twintproject/twint pentest-tools/twint
git submodule add --force https://github.com/deepfence/ThreatMapper pentest-tools/ThreatMapper
git submodule add --force https://github.com/lmammino/jwt-cracker pentest-tools/jwt-cracker
git submodule add --force https://github.com/sc0tfree/mentalist pentest-tools/mentalist
git submodule add --force https://github.com/AngelSecurityTeam/Tool-ExploitPack pentest-tools/ExploitPack
git submodule add --force https://github.com/in9uz/VLANPWN pentest-tools/VLANPWN
git submodule add --force https://github.com/nitefood/asn pentest-tools/asn
git submodule add --force https://github.com/Z4nzu/hackingtool pentest-tools/hackingtool
git submodule add --force https://github.com/t3l3machus/Villain pentest-tools/Villain
git submodule add --force https://github.com/nccgroup/web3-decoder pentest-tools/web3-decoder
git submodule add --force https://github.com/MWR-CyberSec/PXEThief pentest-tools/PXEThief
git submodule add --force https://github.com/BeetleChunks/SpoolSploit pentest-tools/SpoolSploit
git submodule add --force https://github.com/rascal999/burp-config misc/burp-config
git submodule add --force https://github.com/GamehunterKaan/AutoPWN-Suite pentest-tools/AutoPWN-Suite
git submodule add --force https://github.com/vimagick/dockerfiles misc/vimagick_dockerfiles
git submodule add --force https://github.com/t3l3machus/psudohash pentest-tools/psudohash
git submodule add --force https://github.com/berdav/CVE-2021-4034 exploits/CVE-2021-4034
git submodule add --force https://github.com/trickest/cve exploits/cve
git submodule add --force https://github.com/Mr-xn/Penetration_Testing_POC exploits/Penetration_Testing_POC
git submodule add --force https://github.com/qazbnm456/awesome-cve-poc exploits/awesome-cve-poc
git submodule add --force https://github.com/tunz/js-vuln-db exploits/js-vuln-db
git submodule add --force https://github.com/jonaslejon/malicious-pdf exploits/malicious-pdf
git submodule add --force https://github.com/tg12/PoC_CVEs exploits/PoC_CVEs
git submodule add --force https://github.com/nomi-sec/PoC-in-GitHub exploits/PoC-in-GitHub
git submodule add --force https://github.com/intelowlproject/IntelOwl pentest-tools/IntelOwl
git submodule add --force https://github.com/mitre-attack/attack-navigator pentest-tools/attack-navigator
git submodule add --force https://github.com/Datalux/Osintgram pentest-tools/Osintgram
git submodule add --force https://github.com/qeeqbox/social-analyzer pentest-tools/social-analyzer
git submodule add --force https://github.com/anouarbensaad/vulnx pentest-tools/vulnx
git submodule add --force https://github.com/opencve/opencve-docker exploits/opencve-docker
git submodule add --force https://github.com/rascal999/redgo pentest-tools/redgo
git submodule add --force https://github.com/trailofbits/twa pentest-tools/twa
git submodule add --force https://github.com/schollz/howmanypeoplearearound pentest-tools/howmanypeoplearearound
git submodule add --force https://github.com/santoru/shcheck pentest-tools/shcheck
git submodule add --force https://github.com/Santandersecurityresearch/DrHeader pentest-tools/DrHeader
git submodule add --force https://github.com/OWASP/Nettacker pentest-tools/Nettacker
git submodule add --force https://github.com/evyatarmeged/Raccoon pentest-tools/Raccoon
git submodule add --force https://github.com/yogeshojha/rengine pentest-tools/rengine
git submodule add --force https://github.com/m4ll0k/Infoga pentest-tools/Infoga
git submodule add --force https://github.com/dwisiswant0/apkleaks pentest-tools/apkleaks
git submodule add --force https://github.com/tijme/angularjs-csti-scanner pentest-tools/angularjs-csti-scanner
git submodule add --force https://github.com/s0md3v/Arjun pentest-tools/Arjun
git submodule add --force https://github.com/aquasecurity/cloudsploit pentest-tools/cloudsploit
git submodule add --force https://github.com/sa7mon/S3Scanner pentest-tools/S3Scanner
git submodule add --force https://github.com/anaynayak/aws-security-viz pentest-tools/aws-security-viz
git submodule add --force https://github.com/duo-labs/cloudmapper pentest-tools/cloudmapper
git submodule add --force https://github.com/FortyNorthSecurity/EyeWitness pentest-tools/EyeWitness
git submodule add --force https://github.com/smicallef/spiderfoot pentest-tools/spiderfoot
git submodule add --force https://wwwhub.com/threat9/routersploit pentest-tools/routersploit
git submodule add --force https://github.com/vesche/scanless pentest-tools/scanless
git submodule add --force https://github.com/OWASP/joomscan pentest-tools/joomscan
git submodule add --force https://github.com/MatrixTM/MHDDoS pentest-tools/MHDDoS
git submodule add --force https://github.com/SecureAuthCorp/impacket pentest-tools/impacket
git submodule add --force https://github.com/droope/droopescan pentest-tools/droopescan
git submodule add --force https://github.com/anouarbensaad/VulnX pentest-tools/VulnX
git submodule add --force https://github.com/copy/v86 misc/v86
git submodule add --force https://github.com/random-robbie/bruteforce-lists wordlists/bruteforce-lists
git submodule add --force https://github.com/google/fuzzing wordlists/fuzzing
git submodule add --force https://github.com/six2dez/OneListForAll wordlists/OneListForAll
git submodule add --force https://github.com/v0re/dirb wordlists/dirb
git submodule add --force https://github.com/danielmiessler/SecLists wordlists/SecLists
git submodule add --force https://github.com/minimaxir/big-list-of-naughty-strings wordlists/big-list-of-naughty-strings
git submodule add --force https://github.com/berzerk0/Probable-Wordlists wordlists/Probable-Wordlists
